export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const TOGGLE_AUTH_MODAL = "TOGGLE_AUTH_MODAL";